import { CircleDot, Copy, Download, FileArchive, FileImage, FilePenLine, FileText, FolderKanban, Pencil, Play, Save, Trash2, X } from "lucide-react";
import { useMemo, useState } from "react";
import { downloadArtifact, type SupportedExtension } from "@/lib/fileActions";
import type { LocalEntry, LocalProject } from "@/lib/localLibrary";

type Labels = { title: string; description: string; noProjects: string; outputs: string; sources: string; download: string; copy: string; inspectSources: string; edit: string; editContent: string; delete: string; rerun: string; removeSource: string; save: string; cancel: string; projectName: string; sourceList: string; outputList: string; confidence: string; review: string; created: string; };
type NameTarget = { kind: "project"; id: string; name: string } | { kind: "source"; id: string; name: string };
type ConfirmTarget = { kind: "project"; project: LocalProject } | { kind: "source"; project: LocalProject; entryId: string; name: string };
type Props = { projects: LocalProject[]; entries: LocalEntry[]; labels: Labels; onRenameProject: (id: string, name: string) => Promise<void>; onCopyProject: (id: string) => Promise<void>; onDeleteProject: (id: string) => Promise<void>; onRemoveSource: (project: LocalProject, entryId: string) => Promise<void>; onRenameSource: (entryId: string, name: string) => Promise<void>; onEditSourceContent: (entryId: string, content: string) => Promise<void>; onRerun: (project: LocalProject) => Promise<void>; };
const iconFor = (extension?: SupportedExtension | null) => extension === "jpg" ? FileImage : extension === "cbz" ? FileArchive : FileText;

export function ProjectControlPanel({ projects, entries, labels, onRenameProject, onCopyProject, onDeleteProject, onRemoveSource, onRenameSource, onEditSourceContent, onRerun }: Props) {
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [nameTarget, setNameTarget] = useState<NameTarget | null>(null);
  const [draftName, setDraftName] = useState("");
  const [confirmTarget, setConfirmTarget] = useState<ConfirmTarget | null>(null);
  const [contentTarget, setContentTarget] = useState<LocalEntry | null>(null);
  const [contentDraft, setContentDraft] = useState("");
  const selected = useMemo(() => projects.find((project) => project.id === selectedId) ?? null, [projects, selectedId]);
  const outputs = selected ? selected.outputEntryIds.map((id) => entries.find((entry) => entry.id === id)).filter((entry): entry is LocalEntry => Boolean(entry)) : [];
  const sources = selected ? selected.sourceEntryIds.map((id) => entries.find((entry) => entry.id === id)).filter((entry): entry is LocalEntry => Boolean(entry)) : [];
  const startNaming = (target: NameTarget) => { setNameTarget(target); setDraftName(target.name); };
  const download = (entry: LocalEntry) => { if (entry.blob && entry.extension && entry.mimeType) downloadArtifact({ name: entry.name, extension: entry.extension, mimeType: entry.mimeType, blob: entry.blob, description: "Project file." }); };
  const saveName = async () => { if (!nameTarget || !draftName.trim()) return; if (nameTarget.kind === "project") await onRenameProject(nameTarget.id, draftName); else await onRenameSource(nameTarget.id, draftName); setNameTarget(null); };
  const confirmAction = async () => { if (!confirmTarget) return; if (confirmTarget.kind === "project") { await onDeleteProject(confirmTarget.project.id); if (selectedId === confirmTarget.project.id) setSelectedId(null); } else await onRemoveSource(confirmTarget.project, confirmTarget.entryId); setConfirmTarget(null); };
  const beginContentEdit = async (entry: LocalEntry) => { if (!entry.blob) return; setContentDraft(await entry.blob.text()); setContentTarget(entry); };

  return <section className="project-control-panel" id="projects"><div className="project-panel-head"><div><p className="section-label">{labels.title.toUpperCase()}</p><h2>{labels.title}</h2><p>{labels.description}</p></div></div>{projects.length === 0 ? <div className="project-empty"><FolderKanban size={21} />{labels.noProjects}</div> : <div className="project-grid">{projects.map((project) => <article className={`project-card ${selectedId === project.id ? "selected" : ""}`} key={project.id}><button className="project-card-main" onClick={() => setSelectedId(project.id)}><span className="project-orbit"><CircleDot size={17} /></span><span><b>{project.name}</b><small>{project.operation} · {project.outputEntryIds.length} {labels.outputs}</small></span></button><div className="project-card-actions"><button title={labels.download} onClick={() => { const output = project.outputEntryIds.map((id) => entries.find((entry) => entry.id === id))[0]; if (output) download(output); }}><Download size={15} /></button><button title={labels.inspectSources} onClick={() => setSelectedId(project.id)}><Pencil size={15} /></button><button title={labels.copy} onClick={() => void onCopyProject(project.id)}><Copy size={15} /></button><button title={labels.delete} className="danger" onClick={() => setConfirmTarget({ kind: "project", project })}><Trash2 size={15} /></button></div></article>)}</div>}
    {selected && <div className="project-detail-overlay" onMouseDown={() => setSelectedId(null)}><div className="project-detail" onMouseDown={(event) => event.stopPropagation()}><button className="choice-close" onClick={() => setSelectedId(null)}><X size={18} /></button><div className="project-detail-head"><span className="project-orbit"><CircleDot size={17} /></span><div><p className="section-label">{selected.operation.toUpperCase()}</p><h3>{selected.name}</h3><small>{new Date(selected.updatedAt).toLocaleString()}</small></div><button className="secondary-button" onClick={() => startNaming({ kind: "project", id: selected.id, name: selected.name })}><Pencil size={14} />{labels.edit}</button></div><div className="project-detail-columns"><section><div className="detail-title"><h4>{labels.outputList}</h4><span>{outputs.length}</span></div>{outputs.map((entry) => { const Icon = iconFor(entry.extension); return <div className="project-file-row" key={entry.id}><span><Icon size={16} /></span><b>{entry.name}.{entry.extension}</b><button title={labels.download} onClick={() => download(entry)}><Download size={15} /></button></div>; })}</section><section><div className="detail-title"><h4>{labels.sourceList}</h4><span>{sources.length}</span></div>{sources.map((entry) => { const Icon = iconFor(entry.extension); const editable = entry.extension === "txt" || entry.extension === "html"; return <div className="project-file-row" key={entry.id}><span><Icon size={16} /></span><b>{entry.name}.{entry.extension}</b><button title={labels.download} onClick={() => download(entry)}><Download size={15} /></button>{editable && <button title={labels.editContent} onClick={() => void beginContentEdit(entry)}><FilePenLine size={14} /></button>}<button title={labels.edit} onClick={() => startNaming({ kind: "source", id: entry.id, name: entry.name })}><Pencil size={14} /></button><button title={labels.removeSource} className="danger" onClick={() => setConfirmTarget({ kind: "source", project: selected, entryId: entry.id, name: entry.name })}><Trash2 size={14} /></button></div>; })}</section></div><button className="primary-button rerun-project" onClick={() => void onRerun(selected)}><Play size={15} />{labels.rerun}</button></div></div>}
    {nameTarget && <div className="choice-overlay" onMouseDown={() => setNameTarget(null)}><div className="project-name-dialog" onMouseDown={(event) => event.stopPropagation()}><button className="choice-close" onClick={() => setNameTarget(null)}><X size={18} /></button><p className="section-label">{labels.edit.toUpperCase()}</p><h3>{labels.projectName}</h3><input autoFocus value={draftName} onChange={(event) => setDraftName(event.target.value)} /><div><button className="secondary-button" onClick={() => setNameTarget(null)}>{labels.cancel}</button><button className="primary-button compact" onClick={() => void saveName()}><Save size={15} />{labels.save}</button></div></div></div>}
    {confirmTarget && <div className="choice-overlay" onMouseDown={() => setConfirmTarget(null)}><div className="project-name-dialog confirm-dialog" onMouseDown={(event) => event.stopPropagation()}><button className="choice-close" onClick={() => setConfirmTarget(null)}><X size={18} /></button><p className="section-label">{labels.delete.toUpperCase()}</p><h3>{confirmTarget.kind === "project" ? confirmTarget.project.name : confirmTarget.name}</h3><p>{confirmTarget.kind === "project" ? `${labels.delete} ${labels.outputs}?` : `${labels.removeSource}?`}</p><div><button className="secondary-button" onClick={() => setConfirmTarget(null)}>{labels.cancel}</button><button className="danger-button" onClick={() => void confirmAction()}><Trash2 size={15} />{labels.delete}</button></div></div></div>}
    {contentTarget && <div className="choice-overlay" onMouseDown={() => setContentTarget(null)}><div className="project-name-dialog content-editor" onMouseDown={(event) => event.stopPropagation()}><button className="choice-close" onClick={() => setContentTarget(null)}><X size={18} /></button><p className="section-label">{labels.editContent.toUpperCase()}</p><h3>{contentTarget.name}.{contentTarget.extension}</h3><textarea value={contentDraft} onChange={(event) => setContentDraft(event.target.value)} /><div><button className="secondary-button" onClick={() => setContentTarget(null)}>{labels.cancel}</button><button className="primary-button compact" onClick={() => void onEditSourceContent(contentTarget.id, contentDraft).then(() => setContentTarget(null))}><Save size={15} />{labels.save}</button></div></div></div>}
  </section>;
}
